<?php

use App\Http\Controllers\Api\AdminAnalyticsController;
use App\Http\Controllers\Api\AdminLessonsController;
use App\Http\Controllers\Api\AdminOpsController;
use App\Http\Controllers\Api\AmericanoController;
use App\Http\Controllers\Api\AppInfoController;
use App\Http\Controllers\Api\AuthExtrasController;
use App\Http\Controllers\Api\BookingsController;
use App\Http\Controllers\Api\CatalogController;
use App\Http\Controllers\Api\CoachPortalController;
use App\Http\Controllers\Api\DataRightsController;
use App\Http\Controllers\Api\DiscoveryController;
use App\Http\Controllers\Api\EngagementController;
use App\Http\Controllers\Api\FeedController;
use App\Http\Controllers\Api\GamesController;
use App\Http\Controllers\Api\HealthController;
use App\Http\Controllers\Api\InternalController;
use App\Http\Controllers\Api\InvitationsController;
use App\Http\Controllers\Api\LaunchWaitlistController;
use App\Http\Controllers\Api\LessonsController;
use App\Http\Controllers\Api\MatchController;
use App\Http\Controllers\Api\MeController;
use App\Http\Controllers\Api\MediaController;
use App\Http\Controllers\Api\MedicalController;
use App\Http\Controllers\Api\MembershipController;
use App\Http\Controllers\Api\MessagingController;
use App\Http\Controllers\Api\MiscController;
use App\Http\Controllers\Api\MobileController;
use App\Http\Controllers\Api\OAuthController;
use App\Http\Controllers\Api\OgController;
use App\Http\Controllers\Api\OwnerApplicationsController;
use App\Http\Controllers\Api\PartnerLessonsController;
use App\Http\Controllers\Api\PartnerOpsController;
use App\Http\Controllers\Api\PaymentsController;
use App\Http\Controllers\Api\PreferencesController;
use App\Http\Controllers\Api\PromoCodesController;
use App\Http\Controllers\Api\ReferralsController;
use App\Http\Controllers\Api\ReportsController;
use App\Http\Controllers\Api\SeriesController;
use App\Http\Controllers\Api\SocialController;
use App\Http\Controllers\Api\SquadsController;
use App\Http\Controllers\Api\StoriesController;
use App\Http\Controllers\Api\SupportController;
use App\Http\Controllers\Api\TournamentsController;
use App\Http\Controllers\Api\VenueReviewsController;
use App\Http\Controllers\Api\WaitlistController;
use App\Http\Controllers\Api\WebController;
use App\Http\Controllers\AuthController;
use Illuminate\Support\Facades\Route;

/*
 * API routes use full paths because bootstrap/app.php disables Laravel's
 * default apiPrefix. The goal is stable wire compatibility for clients.
 */

Route::get('/health', [HealthController::class, 'health']);
Route::get('/health/ready', [HealthController::class, 'ready']);
Route::get('/.well-known/apple-app-site-association', [AppInfoController::class, 'appleAppSiteAssociation']);
Route::get('/og/{path?}', [OgController::class, 'image'])->where('path', '.*');

Route::prefix('api/v1')->group(function () {
    Route::prefix('internal')->middleware('internal.key')->group(function () {
        Route::get('capabilities', [InternalController::class, 'capabilities']);
    });

    Route::post('auth/register', [AuthController::class, 'register'])->middleware('throttle:5,1');
    Route::post('auth/login', [AuthController::class, 'login'])->middleware('throttle:login');
    Route::post('auth/admin/login', [AuthController::class, 'adminLogin'])->middleware('throttle:5,1');
    Route::post('auth/owner/login', [AuthController::class, 'ownerLogin'])->middleware('throttle:5,1');
    Route::post('auth/coach/login', [AuthController::class, 'coachLogin'])->middleware('throttle:5,1');
    Route::post('auth/refresh', [AuthController::class, 'refresh'])->middleware('throttle:20,1');
    Route::post('auth/logout', [AuthController::class, 'logout'])->middleware('throttle:20,1');
    Route::post('auth/verify-email', [AuthExtrasController::class, 'verifyEmail'])->middleware('throttle:10,1');
    Route::post('auth/request-password-reset', [AuthExtrasController::class, 'requestPasswordReset'])->middleware('throttle:password-reset-request');
    Route::post('auth/verify-password-reset-code', [AuthExtrasController::class, 'verifyPasswordResetCode'])->middleware('throttle:password-reset');
    Route::post('auth/reset-password', [AuthExtrasController::class, 'resetPassword'])->middleware('throttle:password-reset');
    Route::post('auth/apple', [OAuthController::class, 'apple'])->middleware('throttle:10,1');
    Route::post('auth/google', [OAuthController::class, 'google'])->middleware('throttle:10,1');
    // Public email/username availability oracle — tight throttle (matches the
    // other sensitive auth routes) so it cannot be enumerated en masse.
    Route::get('auth/check', [MobileController::class, 'authCheck'])->middleware('throttle:10,1');

    Route::get('app/version', [AppInfoController::class, 'version']);
    Route::get('app/metadata', [AppInfoController::class, 'metadata']);
    Route::get('app/capabilities', [AppInfoController::class, 'capabilities']);
    Route::post('launch-waitlist', [LaunchWaitlistController::class, 'store'])->middleware('throttle:10,1');
    Route::post('support/contact', [SupportController::class, 'publicCreate'])->middleware('throttle:10,1');
    Route::get('mobile/config', [MobileController::class, 'config']);
    Route::get('membership/plans', [MembershipController::class, 'plans']);
    Route::get('links/resolve', [MobileController::class, 'resolveLink'])->middleware('throttle:public-discovery');
    Route::get('sports', [CatalogController::class, 'sports']);
    Route::get('venues', [CatalogController::class, 'venues'])->middleware('throttle:public-discovery');
    Route::get('courts', [CatalogController::class, 'courts'])->middleware('throttle:public-discovery');
    Route::get('venues/{id}/availability', [CatalogController::class, 'venueAvailability'])->middleware('throttle:public-discovery');
    Route::get('venues/{id}', [CatalogController::class, 'venue'])->middleware('throttle:public-discovery');
    Route::get('courts/{id}', [CatalogController::class, 'court'])->middleware('throttle:public-discovery');
    Route::get('courts/{id}/availability', [BookingsController::class, 'availability'])->middleware('throttle:public-discovery');
    Route::get('courts/{id}/suggested-slots', [BookingsController::class, 'suggestedSlots'])->middleware('throttle:public-discovery');
    Route::post('bookings/quote', [BookingsController::class, 'quote'])->middleware('throttle:write-action');
    Route::post('promo-codes/validate', [PromoCodesController::class, 'validateCode'])->middleware('throttle:write-action');
    Route::get('games', [GamesController::class, 'index'])->middleware('throttle:public-discovery');
    Route::get('games/{id}', [GamesController::class, 'show'])->middleware('throttle:public-discovery');
    Route::get('players', [SocialController::class, 'players'])->middleware('throttle:public-discovery');
    Route::get('search', [SocialController::class, 'search'])->middleware('throttle:public-discovery');
    Route::get('feed', [FeedController::class, 'index'])->middleware('throttle:public-discovery');
    Route::get('feed/{eventId}/comments', [FeedController::class, 'comments'])->middleware('throttle:public-discovery');
    Route::get('leaderboards/elo', [EngagementController::class, 'leaderboards'])->middleware('throttle:public-discovery');
    Route::get('rankings', [EngagementController::class, 'leaderboards'])->middleware('throttle:public-discovery');
    Route::get('realtime/health', [MiscController::class, 'realtimeHealth']);
    Route::get('realtime/sse', [MiscController::class, 'realtimeSse'])->middleware('throttle:60,1');
    Route::post('analytics/events', [MiscController::class, 'analytics'])->middleware('throttle:120,1');
    Route::get('tournaments', [TournamentsController::class, 'index'])->middleware('throttle:public-discovery');
    Route::get('tournaments/{id}', [TournamentsController::class, 'show'])->middleware('throttle:public-discovery');
    Route::get('users/{id}/profile', [SocialController::class, 'profile'])->middleware('throttle:public-discovery');
    Route::get('users/{id}/followers', [SocialController::class, 'followers'])->middleware('throttle:public-discovery');
    Route::get('users/{id}/following', [SocialController::class, 'following'])->middleware('throttle:public-discovery');
    Route::get('users/{id}/achievements', [EngagementController::class, 'achievements'])->middleware('throttle:public-discovery');
    Route::get('users/{id}/streaks', [EngagementController::class, 'streaks'])->middleware('throttle:public-discovery');
    Route::get('venues/{id}/reviews', [VenueReviewsController::class, 'index'])->middleware('throttle:public-discovery');
    Route::get('venues/{id}/rating-summary', [VenueReviewsController::class, 'summary'])->middleware('throttle:public-discovery');
    // "Learn" — public browse of lessons (classes) + coaches (optional Bearer token).
    Route::get('lessons', [LessonsController::class, 'index'])->middleware('throttle:public-discovery');
    Route::get('lessons/{id}', [LessonsController::class, 'show'])->middleware('throttle:public-discovery');
    Route::get('coaches', [LessonsController::class, 'coaches'])->middleware('throttle:public-discovery');
    Route::get('coaches/{id}', [LessonsController::class, 'coach'])->middleware('throttle:public-discovery');
    Route::get('stats', [WebController::class, 'publicStats'])->middleware('throttle:public-discovery');
    Route::get('web/bootstrap', [WebController::class, 'bootstrap']);
    Route::get('web/checkout/courts/{courtId}', [WebController::class, 'checkout'])->middleware('throttle:public-discovery');

    // jwt authenticates + sets auth_user; PortalRoleGuard then enforces role by
    // path prefix (admin/partner/owner/coach) as defense-in-depth on top of the
    // in-controller checks. It passes through all consumer (non-portal) paths.
    Route::middleware(['jwt', \App\Http\Middleware\PortalRoleGuard::class])->group(function () {
        Route::post('auth/send-verification', [AuthExtrasController::class, 'sendVerification'])->middleware('throttle:3,1');
        Route::get('me', [MeController::class, 'show']);
        Route::get('mobile/bootstrap', [MobileController::class, 'bootstrap']);
        Route::get('web/dashboard', [WebController::class, 'dashboard']);
        Route::patch('me', [MeController::class, 'update']);
        Route::post('me/avatar', [MeController::class, 'avatar'])->middleware('throttle:30,1');
        Route::delete('me/avatar', [MeController::class, 'deleteAvatar']);
        Route::post('me/change-password', [MeController::class, 'changePassword'])->middleware('throttle:5,1');
        Route::post('me/change-email', [MeController::class, 'changeEmail'])->middleware('throttle:5,1');
        Route::delete('me', [DataRightsController::class, 'requestDeletion']);
        Route::get('me/sessions', [MeController::class, 'sessions']);
        Route::delete('me/sessions/{id}', [MeController::class, 'deleteSession']);
        Route::delete('me/sessions', [MeController::class, 'deleteOtherSessions']);
        Route::get('me/devices', [MeController::class, 'deviceList']);
        Route::post('me/devices', [MeController::class, 'devices']);
        Route::post('me/devices/test-push', [MeController::class, 'testPush'])->middleware('throttle:5,1');
        Route::delete('me/devices/{idOrToken}', [MeController::class, 'deleteDevice']);
        Route::get('me/notification-preferences', [PreferencesController::class, 'show']);
        Route::patch('me/notification-preferences', [PreferencesController::class, 'patch']);
        Route::put('me/notification-preferences/quiet-hours', [PreferencesController::class, 'quietHours']);
        Route::put('me/notification-preferences/daily-digest', [PreferencesController::class, 'dailyDigest']);
        Route::get('me/announcements', [EngagementController::class, 'announcements']);
        Route::post('me/announcements/{id}/dismiss', [EngagementController::class, 'dismissAnnouncement']);
        Route::get('me/activity', [DiscoveryController::class, 'activity']);
        Route::get('support/tickets', [SupportController::class, 'mine']);
        Route::post('support/tickets', [SupportController::class, 'create']);
        Route::get('support/tickets/{id}', [SupportController::class, 'show']);
        Route::post('support/tickets/{id}/messages', [SupportController::class, 'addMessage']);
        Route::post('support/tickets/{id}/close', [SupportController::class, 'close']);
        Route::get('owner/applications', [OwnerApplicationsController::class, 'mine']);
        Route::post('owner/applications', [OwnerApplicationsController::class, 'create']);
        Route::get('me/saved-venues', [CatalogController::class, 'savedVenues']);
        Route::post('venues/{id}/save', [CatalogController::class, 'saveVenue']);
        Route::delete('venues/{id}/save', [CatalogController::class, 'unsaveVenue']);
        Route::get('me/saved-courts', [CatalogController::class, 'savedCourts']);
        Route::post('courts/{id}/save', [CatalogController::class, 'saveCourt']);
        Route::delete('courts/{id}/save', [CatalogController::class, 'unsaveCourt']);
        Route::get('me/waitlist', [WaitlistController::class, 'mine']);
        Route::post('courts/{id}/waitlist', [WaitlistController::class, 'create'])->middleware('throttle:write-action');
        Route::delete('waitlist/{id}', [WaitlistController::class, 'cancel']);
        Route::get('booking-holds', [BookingsController::class, 'holds']);
        Route::post('booking-holds', [BookingsController::class, 'createHold'])->middleware('throttle:write-action');
        Route::delete('booking-holds/{id}', [BookingsController::class, 'releaseHold']);
        Route::get('admin/announcements', [EngagementController::class, 'adminAnnouncements']);
        Route::post('admin/announcements', [EngagementController::class, 'createAnnouncement']);
        Route::get('admin/announcements/{id}', [EngagementController::class, 'adminAnnouncement']);
        Route::patch('admin/announcements/{id}', [EngagementController::class, 'updateAnnouncement']);
        Route::post('admin/announcements/{id}/expire', [EngagementController::class, 'expireAnnouncement']);
        Route::delete('admin/announcements/{id}', [EngagementController::class, 'deleteAnnouncement']);
        Route::get('me/agenda', [DiscoveryController::class, 'agenda']);
        Route::get('me/insights', [DiscoveryController::class, 'insights']);
        Route::get('me/home', [DiscoveryController::class, 'home']);
        Route::get('me/suggested-follows', [DiscoveryController::class, 'suggestedFollows']);
        Route::get('me/matchmaking/games', [DiscoveryController::class, 'matchmakingGames']);
        Route::get('me/matchmaking/players', [DiscoveryController::class, 'matchmakingPlayers']);
        Route::get('me/matchmaking/players/for-me', [DiscoveryController::class, 'matchmakingPlayers']);
        Route::get('me/challenges/today', [DiscoveryController::class, 'challenges']);
        Route::post('me/challenges/{code}/check', [DiscoveryController::class, 'checkChallenge']);
        Route::post('me/delete', [DataRightsController::class, 'requestDeletion'])->middleware('throttle:5,60');
        Route::post('me/delete/cancel', [DataRightsController::class, 'cancelDeletion'])->middleware('throttle:10,60');
        Route::get('me/delete', [DataRightsController::class, 'deletionStatus']);
        Route::post('me/data-export', [DataRightsController::class, 'requestExport'])->middleware('throttle:5,60');
        Route::get('me/data-export', [DataRightsController::class, 'latestExport']);
        Route::get('me/medical-profile', [MedicalController::class, 'show']);
        Route::put('me/medical-profile', [MedicalController::class, 'update']);
        Route::get('me/referral', [ReferralsController::class, 'card']);
        Route::get('me/referrals', [ReferralsController::class, 'mine']);
        Route::get('me/referrals/share', [ReferralsController::class, 'share']);
        Route::post('auth/redeem-referral', [ReferralsController::class, 'redeem'])->middleware('throttle:10,1');
        Route::get('me/membership', [MembershipController::class, 'show']);
        Route::post('membership/subscribe', [MembershipController::class, 'subscribe'])->middleware('throttle:write-action');
        Route::post('me/membership/portal', [MembershipController::class, 'portal'])->middleware('throttle:write-action');
        Route::post('membership/cancel', [MembershipController::class, 'cancel'])->middleware('throttle:write-action');
        Route::get('payments/history', [PaymentsController::class, 'history']);
        Route::get('payments/summary', [PaymentsController::class, 'summary']);
        Route::post('payments/booking/{id}/intent', [PaymentsController::class, 'bookingIntent'])->middleware('throttle:write-action');
        Route::get('payments/booking/{id}/status', [PaymentsController::class, 'bookingStatus']);
        Route::post('payments/tournament/{tournamentId}/entry-intent', [PaymentsController::class, 'tournamentIntent'])->middleware('throttle:write-action');
        Route::post('game-series', [SeriesController::class, 'store'])->middleware('throttle:write-action');
        Route::get('game-series/{id}', [SeriesController::class, 'show']);
        Route::post('game-series/{id}/cancel', [SeriesController::class, 'cancel'])->middleware('throttle:write-action');
        Route::post('americano/tournaments', [AmericanoController::class, 'store'])->middleware('throttle:write-action');
        Route::get('americano/tournaments', [AmericanoController::class, 'index']);
        Route::get('americano/tournaments/my', [AmericanoController::class, 'mine']);
        Route::get('americano/tournaments/{id}', [AmericanoController::class, 'show']);
        Route::post('americano/tournaments/{id}/teams', [AmericanoController::class, 'teams'])->middleware('throttle:write-action');
        Route::post('americano/tournaments/{id}/start', [AmericanoController::class, 'start'])->middleware('throttle:write-action');
        Route::post('americano/matches/{id}/score', [AmericanoController::class, 'score'])->middleware('throttle:write-action');
        Route::get('partner/account', [PartnerOpsController::class, 'account']);
        Route::patch('partner/account', [PartnerOpsController::class, 'updateAccount']);
        Route::get('partner/bootstrap', [PartnerOpsController::class, 'bootstrap']);
        Route::get('partner/lookups', [PartnerOpsController::class, 'lookups']);
        Route::get('partner/venue', [PartnerOpsController::class, 'venue']);
        Route::put('partner/venue', [PartnerOpsController::class, 'updateVenue']);
        Route::get('partner/courts', [PartnerOpsController::class, 'courts']);
        Route::post('partner/courts', [PartnerOpsController::class, 'createCourt']);
        Route::get('partner/courts/{id}', [PartnerOpsController::class, 'court']);
        Route::put('partner/courts/{id}', [PartnerOpsController::class, 'updateCourt']);
        Route::delete('partner/courts/{id}', [PartnerOpsController::class, 'deleteCourt']);

        // "Learn" — player actions + club-side coach/lesson management.
        Route::get('me/lessons', [LessonsController::class, 'mine']);
        Route::post('lessons/{id}/book', [LessonsController::class, 'book']);
        Route::delete('lessons/{id}/book', [LessonsController::class, 'cancel']);
        Route::get('partner/coaches', [PartnerLessonsController::class, 'coaches']);
        Route::post('partner/coaches', [PartnerLessonsController::class, 'createCoach']);
        Route::put('partner/coaches/{id}', [PartnerLessonsController::class, 'updateCoach']);
        Route::delete('partner/coaches/{id}', [PartnerLessonsController::class, 'deleteCoach']);
        Route::get('partner/lessons', [PartnerLessonsController::class, 'lessons']);
        Route::post('partner/lessons', [PartnerLessonsController::class, 'createLesson']);
        Route::put('partner/lessons/{id}', [PartnerLessonsController::class, 'updateLesson']);
        Route::delete('partner/lessons/{id}', [PartnerLessonsController::class, 'deleteLesson']);
        Route::get('partner/lessons/{id}/bookings', [PartnerLessonsController::class, 'roster']);
        Route::get('partner/today', [PartnerOpsController::class, 'today']);
        Route::get('partner/activity', [PartnerOpsController::class, 'activity']);
        Route::get('partner/customers', [PartnerOpsController::class, 'customers']);
        Route::get('partner/users/search', [PartnerOpsController::class, 'userSearch']);
        Route::get('partner/reviews', [VenueReviewsController::class, 'partnerIndex']);
        Route::post('partner/reviews/{id}/remove', [VenueReviewsController::class, 'partnerRemove']);
        Route::post('partner/reviews/{id}/restore', [VenueReviewsController::class, 'partnerRestore']);
        Route::get('partner/metrics', [PartnerOpsController::class, 'metrics']);
        Route::get('partner/availability', [PartnerOpsController::class, 'availability']);
        Route::get('partner/bookings', [PartnerOpsController::class, 'bookings']);
        Route::get('partner/bookings/export', [PartnerOpsController::class, 'exportBookings']);
        Route::get('partner/booking-holds', [BookingsController::class, 'partnerHolds']);
        Route::get('partner/waitlist', [WaitlistController::class, 'partnerIndex']);
        Route::patch('partner/waitlist/{id}', [WaitlistController::class, 'partnerUpdate']);
        Route::post('partner/bookings/quote', [PartnerOpsController::class, 'quoteBooking']);
        Route::post('partner/bookings/bulk-status', [PartnerOpsController::class, 'bulkUpdateBookings']);
        Route::get('partner/bookings/{id}', [PartnerOpsController::class, 'booking']);
        Route::patch('partner/bookings/{id}', [PartnerOpsController::class, 'updateBooking']);
        Route::post('partner/bookings/{id}/cancel', [PartnerOpsController::class, 'cancelBooking']);
        Route::post('partner/bookings/{id}/mark-paid', [PartnerOpsController::class, 'markPaid']);
        Route::post('partner/bookings/{id}/refund', [PartnerOpsController::class, 'refundBooking']);
        Route::post('partner/bookings/{id}/no-show', [PartnerOpsController::class, 'markNoShow']);
        Route::post('partner/bookings/{id}/clear-no-show', [PartnerOpsController::class, 'clearNoShow']);
        Route::post('partner/bookings/{id}/check-in', [PartnerOpsController::class, 'checkInBooking']);
        Route::post('partner/bookings/{id}/undo-check-in', [PartnerOpsController::class, 'undoCheckInBooking']);
        Route::post('partner/bookings', [PartnerOpsController::class, 'createBooking']);
        Route::get('partner/stats', [PartnerOpsController::class, 'stats']);
        Route::get('partner/calendar', [PartnerOpsController::class, 'calendar']);
        Route::get('partner/schedule', [PartnerOpsController::class, 'schedule']);
        Route::get('partner/revenue', [PartnerOpsController::class, 'revenue']);
        Route::get('partner/tournaments', [PartnerOpsController::class, 'tournaments']);
        Route::post('partner/tournaments', [PartnerOpsController::class, 'createTournament']);
        Route::get('partner/tournaments/{id}', [PartnerOpsController::class, 'tournament']);
        Route::patch('partner/tournaments/{id}', [PartnerOpsController::class, 'updateTournament']);
        Route::post('partner/tournaments/{id}/cancel', [PartnerOpsController::class, 'cancelTournament']);
        Route::get('partner/tournaments/{id}/entries', [PartnerOpsController::class, 'tournamentEntries']);
        Route::patch('partner/tournaments/{id}/entries/{entryId}', [PartnerOpsController::class, 'updateTournamentEntry']);
        Route::get('partner/rules', [PartnerOpsController::class, 'rules']);
        Route::put('partner/rules', [PartnerOpsController::class, 'updateRules']);
        Route::get('partner/blocks', [PartnerOpsController::class, 'blocks']);
        Route::post('partner/blocks', [PartnerOpsController::class, 'createBlock']);
        Route::patch('partner/blocks/{id}', [PartnerOpsController::class, 'updateBlock']);
        Route::delete('partner/blocks/{id}', [PartnerOpsController::class, 'deleteBlock']);
        Route::get('partner/staff', [PartnerOpsController::class, 'staff']);
        Route::post('partner/staff', [PartnerOpsController::class, 'createStaff']);
        Route::patch('partner/staff/{id}', [PartnerOpsController::class, 'updateStaff']);
        Route::delete('partner/staff/{id}', [PartnerOpsController::class, 'deleteStaff']);
        Route::get('coach/bootstrap', [CoachPortalController::class, 'bootstrap']);
        Route::patch('coach/profile', [CoachPortalController::class, 'updateProfile']);
        Route::get('coach/lessons', [CoachPortalController::class, 'lessons']);
        Route::post('coach/lessons', [CoachPortalController::class, 'createLesson']);
        Route::patch('coach/lessons/{id}', [CoachPortalController::class, 'updateLesson']);
        Route::post('coach/lessons/{id}/cancel', [CoachPortalController::class, 'cancelLesson']);
        Route::get('coach/lessons/{id}/bookings', [CoachPortalController::class, 'roster']);
        Route::get('admin/bootstrap', [AdminOpsController::class, 'bootstrap']);
        Route::get('admin/lookups', [AdminOpsController::class, 'lookups']);
        Route::get('admin/stats', [AdminOpsController::class, 'stats']);
        Route::get('admin/metrics', [AdminOpsController::class, 'metrics']);
        // Deeper analytics / dashboard reports.
        Route::get('admin/analytics/overview', [AdminAnalyticsController::class, 'overview']);
        Route::get('admin/analytics/growth', [AdminAnalyticsController::class, 'growth']);
        Route::get('admin/analytics/clubs', [AdminAnalyticsController::class, 'clubs']);
        Route::get('admin/analytics/engagement', [AdminAnalyticsController::class, 'engagement']);
        Route::get('admin/analytics/funnel', [AdminAnalyticsController::class, 'funnel']);
        Route::get('admin/search', [AdminOpsController::class, 'search']);
        Route::get('admin/activity', [AdminOpsController::class, 'activity']);
        Route::post('admin/alerts', [AdminOpsController::class, 'createAlert']);
        Route::get('admin/notifications', [AdminOpsController::class, 'notifications']);
        Route::post('admin/notifications', [AdminOpsController::class, 'sendNotification']);
        Route::get('admin/notifications/{id}', [AdminOpsController::class, 'notification']);
        Route::post('admin/notifications/{id}/read', [AdminOpsController::class, 'markNotificationRead']);
        Route::post('admin/notifications/{id}/unread', [AdminOpsController::class, 'markNotificationUnread']);
        Route::delete('admin/notifications/{id}', [AdminOpsController::class, 'deleteNotification']);
        Route::get('admin/support/tickets', [SupportController::class, 'adminIndex']);
        Route::get('admin/support/tickets/{id}', [SupportController::class, 'show']);
        Route::patch('admin/support/tickets/{id}', [SupportController::class, 'adminUpdate']);
        Route::post('admin/support/tickets/{id}/messages', [SupportController::class, 'addMessage']);
        Route::get('admin/owner-applications', [OwnerApplicationsController::class, 'adminIndex']);
        Route::get('admin/owner-applications/{id}', [OwnerApplicationsController::class, 'adminShow']);
        Route::post('admin/owner-applications/{id}/approve', [OwnerApplicationsController::class, 'approve']);
        Route::post('admin/owner-applications/{id}/reject', [OwnerApplicationsController::class, 'reject']);
        Route::get('admin/reviews', [VenueReviewsController::class, 'adminIndex']);
        Route::get('admin/reviews/{id}', [VenueReviewsController::class, 'adminShow']);
        Route::post('admin/reviews/{id}/remove', [VenueReviewsController::class, 'adminRemove']);
        Route::post('admin/reviews/{id}/restore', [VenueReviewsController::class, 'adminRestore']);
        Route::get('admin/promo-codes', [PromoCodesController::class, 'adminIndex']);
        Route::post('admin/promo-codes', [PromoCodesController::class, 'adminStore']);
        Route::get('admin/promo-codes/{id}', [PromoCodesController::class, 'adminShow']);
        Route::patch('admin/promo-codes/{id}', [PromoCodesController::class, 'adminUpdate']);
        Route::delete('admin/promo-codes/{id}', [PromoCodesController::class, 'adminDelete']);
        Route::get('admin/users', [AdminOpsController::class, 'users']);
        Route::post('admin/users', [AdminOpsController::class, 'createUser']);
        Route::get('admin/customers', [AdminOpsController::class, 'customers']);
        Route::get('admin/staff', [AdminOpsController::class, 'staffAccounts']);
        Route::post('admin/staff', [AdminOpsController::class, 'createStaffAccount']);
        Route::patch('admin/staff/{id}', [AdminOpsController::class, 'updateStaffAccount']);
        Route::delete('admin/staff/{id}', [AdminOpsController::class, 'deleteStaffAccount']);
        Route::get('admin/users/{id}', [AdminOpsController::class, 'user']);
        Route::post('admin/users/{id}/role', [AdminOpsController::class, 'setRole']);
        Route::post('admin/users/{id}/email-verification', [AdminOpsController::class, 'setEmailVerification']);
        Route::post('admin/users/{id}/vip', [AdminOpsController::class, 'setVip']);
        Route::post('admin/users/{id}/verified-badge', [AdminOpsController::class, 'setVerifiedBadge']);
        Route::post('admin/users/{id}/ambassador', [AdminOpsController::class, 'setAmbassador']);
        Route::post('admin/users/{id}/membership', [AdminOpsController::class, 'setMembership']);
        // "Learn" — admin-wide coach & lesson management (all venues).
        Route::get('admin/coaches', [AdminLessonsController::class, 'coaches']);
        Route::post('admin/coaches', [AdminLessonsController::class, 'createCoach']);
        Route::put('admin/coaches/{id}', [AdminLessonsController::class, 'updateCoach']);
        Route::delete('admin/coaches/{id}', [AdminLessonsController::class, 'deleteCoach']);
        Route::get('admin/lessons', [AdminLessonsController::class, 'lessons']);
        Route::post('admin/lessons', [AdminLessonsController::class, 'createLesson']);
        Route::put('admin/lessons/{id}', [AdminLessonsController::class, 'updateLesson']);
        Route::delete('admin/lessons/{id}', [AdminLessonsController::class, 'deleteLesson']);
        Route::get('admin/lessons/{id}/bookings', [AdminLessonsController::class, 'roster']);
        Route::post('admin/users/{id}/suspend', [AdminOpsController::class, 'suspendUser']);
        Route::post('admin/users/{id}/unsuspend', [AdminOpsController::class, 'unsuspendUser']);
        Route::post('admin/users/{id}/soft-delete', [AdminOpsController::class, 'softDelete']);
        Route::post('admin/users/{id}/restore', [AdminOpsController::class, 'restore']);
        Route::get('admin/games', [AdminOpsController::class, 'games']);
        Route::get('admin/games/{id}', [AdminOpsController::class, 'game']);
        Route::post('admin/games/{id}/cancel', [AdminOpsController::class, 'cancelGame']);
        Route::patch('admin/games/{id}', [AdminOpsController::class, 'updateGame']);
        Route::delete('admin/games/{id}', [AdminOpsController::class, 'deleteGame']);
        Route::post('admin/tournaments', [AdminOpsController::class, 'createTournament']);
        Route::get('admin/tournaments/{id}', [AdminOpsController::class, 'tournament']);
        Route::patch('admin/tournaments/{id}', [AdminOpsController::class, 'updateTournament']);
        Route::delete('admin/tournaments/{id}', [AdminOpsController::class, 'deleteTournament']);
        Route::get('admin/tournaments/{id}/entries', [AdminOpsController::class, 'tournamentEntries']);
        Route::patch('admin/tournaments/{id}/entries/{entryId}', [AdminOpsController::class, 'updateTournamentEntry']);
        Route::delete('admin/tournaments/{id}/entries/{entryId}', [AdminOpsController::class, 'removeTournamentEntry']);
        Route::get('admin/venues', [AdminOpsController::class, 'venues']);
        Route::post('admin/venues', [AdminOpsController::class, 'createVenue']);
        Route::get('admin/venues/{id}', [AdminOpsController::class, 'venue']);
        Route::patch('admin/venues/{id}', [AdminOpsController::class, 'updateVenue']);
        Route::patch('admin/venues/{id}/status', [AdminOpsController::class, 'updateVenueStatus']);
        Route::delete('admin/venues/{id}', [AdminOpsController::class, 'deleteVenue']);
        Route::get('admin/venues/{id}/partners', [AdminOpsController::class, 'partnerAccounts']);
        Route::post('admin/venues/{id}/partners', [AdminOpsController::class, 'createPartnerAccount']);
        Route::patch('admin/venues/{id}/partners/{userId}', [AdminOpsController::class, 'updatePartnerAccount']);
        Route::delete('admin/venues/{id}/partners/{userId}', [AdminOpsController::class, 'deletePartnerAccount']);
        Route::get('admin/venues/{id}/courts', [AdminOpsController::class, 'courts']);
        Route::post('admin/venues/{id}/courts', [AdminOpsController::class, 'createCourt']);
        Route::patch('admin/venues/{id}/courts/{courtId}', [AdminOpsController::class, 'updateCourt']);
        Route::delete('admin/venues/{id}/courts/{courtId}', [AdminOpsController::class, 'deleteCourt']);
        Route::get('admin/courts', [AdminOpsController::class, 'globalCourts']);
        Route::get('admin/courts/{courtId}/blocks', [AdminOpsController::class, 'courtBlocks']);
        Route::post('admin/courts/{courtId}/blocks', [AdminOpsController::class, 'createCourtBlock']);
        Route::patch('admin/courts/{courtId}/blocks/{blockId}', [AdminOpsController::class, 'updateCourtBlock']);
        Route::delete('admin/courts/{courtId}/blocks/{blockId}', [AdminOpsController::class, 'deleteCourtBlock']);
        Route::get('admin/courts/{courtId}', [AdminOpsController::class, 'court']);
        Route::get('admin/tournaments', [AdminOpsController::class, 'tournaments']);
        Route::get('admin/calendar', [AdminOpsController::class, 'calendar']);
        Route::get('admin/revenue', [AdminOpsController::class, 'revenue']);
        Route::get('admin/bookings', [AdminOpsController::class, 'bookings']);
        Route::get('admin/bookings/export', [AdminOpsController::class, 'exportBookings']);
        Route::get('admin/booking-holds', [BookingsController::class, 'adminHolds']);
        Route::get('admin/waitlist', [WaitlistController::class, 'adminIndex']);
        Route::patch('admin/waitlist/{id}', [WaitlistController::class, 'adminUpdate']);
        Route::post('admin/bookings/quote', [AdminOpsController::class, 'quoteBooking']);
        Route::post('admin/bookings', [AdminOpsController::class, 'createBooking']);
        Route::post('admin/bookings/bulk-status', [AdminOpsController::class, 'bulkUpdateBookings']);
        Route::get('admin/bookings/{id}', [AdminOpsController::class, 'booking']);
        Route::patch('admin/bookings/{id}', [AdminOpsController::class, 'updateBooking']);
        Route::get('admin/audit', [AdminOpsController::class, 'audit']);
        Route::get('admin/audit/export', [AdminOpsController::class, 'exportAudit']);
        Route::post('admin/bookings/{id}/cancel', [AdminOpsController::class, 'cancelBooking']);
        Route::post('admin/bookings/{id}/mark-paid', [AdminOpsController::class, 'markPaid']);
        Route::post('admin/bookings/{id}/refund', [AdminOpsController::class, 'refundBooking']);
        Route::post('admin/bookings/{id}/no-show', [AdminOpsController::class, 'markBookingNoShow']);
        Route::post('admin/bookings/{id}/clear-no-show', [AdminOpsController::class, 'clearBookingNoShow']);
        Route::post('admin/bookings/{id}/check-in', [AdminOpsController::class, 'checkInBooking']);
        Route::post('admin/bookings/{id}/undo-check-in', [AdminOpsController::class, 'undoCheckInBooking']);
        Route::get('admin/moderation/reports', [AdminOpsController::class, 'moderationReports']);
        Route::get('admin/moderation/reports/{id}', [ReportsController::class, 'adminShow']);
        Route::post('admin/moderation/reports/{id}/review', [AdminOpsController::class, 'reviewModerationReport']);
        Route::post('admin/reports/{id}/review', [ReportsController::class, 'adminUpdate']);
        Route::get('admin/moderation/users/{id}', [AdminOpsController::class, 'moderationUser']);
        Route::post('admin/moderation/users/{id}/deactivate', [AdminOpsController::class, 'deactivateUser']);
        Route::get('admin/data-rights/deletions', [AdminOpsController::class, 'deletions']);
        Route::post('admin/data-rights/deletions/{userId}/cancel', [AdminOpsController::class, 'cancelDeletion']);
        Route::get('admin/data-rights/exports', [AdminOpsController::class, 'exports']);
        Route::get('admin/operations', [AdminOpsController::class, 'operations']);
        Route::get('admin/push-jobs', [AdminOpsController::class, 'pushJobs']);
        Route::post('admin/push-jobs/{id}/retry', [AdminOpsController::class, 'retryPushJob']);
        Route::post('admin/push-jobs/{id}/cancel', [AdminOpsController::class, 'cancelPushJob']);
        Route::get('admin/media', [AdminOpsController::class, 'media']);
        Route::post('admin/media/cleanup', [AdminOpsController::class, 'cleanupMedia']);
        Route::delete('admin/media/{id}', [AdminOpsController::class, 'deleteMedia']);

        Route::post('games', [GamesController::class, 'store'])->middleware('throttle:write-action');
        Route::patch('games/{id}/reschedule', [GamesController::class, 'reschedule']);
        Route::post('games/{id}/participants/{uid}/no-show', [GamesController::class, 'noShow']);
        Route::patch('games/{id}/participants/{uid}/result-access', [MatchController::class, 'setResultAccess']);
        Route::post('games/{id}/join', [GamesController::class, 'join'])->middleware('throttle:write-action');
        Route::post('games/{id}/leave', [GamesController::class, 'leave']);
        Route::post('games/{id}/cancel', [GamesController::class, 'cancel']);
        Route::post('games/{id}/invitations', [InvitationsController::class, 'batch'])->middleware('throttle:write-action');
        Route::post('games/{id}/invite', [InvitationsController::class, 'create'])->middleware('throttle:write-action');
        Route::get('games/{id}/medical-summary', [MedicalController::class, 'gameSummary']);
        Route::post('games/{id}/ratings', [MatchController::class, 'submitRatings'])->middleware('throttle:write-action');
        Route::post('games/{id}/scoring/start', [MatchController::class, 'startScoring']);
        Route::post('games/{id}/scoring/point', [MatchController::class, 'point']);
        Route::post('games/{id}/scoring/undo', [MatchController::class, 'undo']);
        Route::post('games/{id}/scoring/complete', [MatchController::class, 'complete']);
        Route::post('games/{id}/result', [MatchController::class, 'reportResult'])->middleware('throttle:write-action');
        Route::get('games/{id}/scoring', [MatchController::class, 'scoring']);
        Route::patch('games/{id}', [GamesController::class, 'update']);
        Route::delete('games/{id}', [GamesController::class, 'destroy']);

        Route::post('bookings/{id}/cancel', [BookingsController::class, 'cancel']);
        Route::post('bookings/{id}/mark-paid', [BookingsController::class, 'markPaid']);
        Route::get('bookings', [BookingsController::class, 'index']);
        Route::get('bookings/me', [BookingsController::class, 'mine']);
        Route::get('bookings/me/export', [BookingsController::class, 'exportMine']);
        Route::get('bookings/{id}/receipt', [BookingsController::class, 'receipt']);
        Route::get('bookings/{id}', [BookingsController::class, 'show']);
        Route::patch('bookings/{id}', [BookingsController::class, 'update']);
        Route::post('bookings', [BookingsController::class, 'store'])->middleware('throttle:write-action');

        Route::post('feed/{id}/like', [FeedController::class, 'like']);
        Route::delete('feed/{id}/like', [FeedController::class, 'unlike']);
        Route::post('feed/{eventId}/comments', [FeedController::class, 'storeComment']);
        Route::delete('feed/comments/{commentId}', [FeedController::class, 'deleteComment']);
        Route::get('notifications', [MessagingController::class, 'notifications']);
        Route::get('me/unread-counts', [MessagingController::class, 'unreadCounts']);
        Route::post('notifications/{id}/read', [MessagingController::class, 'markNotificationRead']);
        Route::post('notifications/read-all', [MessagingController::class, 'markAllNotificationsRead']);
        Route::delete('notifications/{id}', [MessagingController::class, 'deleteNotification']);
        Route::delete('notifications', [MessagingController::class, 'deleteNotifications']);
        Route::get('conversations', [MessagingController::class, 'conversations']);
        Route::post('conversations/group', [MessagingController::class, 'openGroupConversation']);
        Route::post('conversations', [MessagingController::class, 'startConversation']);
        Route::get('conversations/{id}', [MessagingController::class, 'thread']);
        Route::delete('conversations/{id}', [MessagingController::class, 'leave']);
        Route::get('conversations/{id}/participants', [MessagingController::class, 'participants']);
        Route::post('conversations/{id}/participants', [MessagingController::class, 'addParticipant']);
        Route::delete('conversations/{id}/participants/{userId}', [MessagingController::class, 'removeParticipant']);
        Route::post('conversations/{id}/messages', [MessagingController::class, 'sendMessage'])->middleware('throttle:write-action');
        Route::post('conversations/{id}/read', [MessagingController::class, 'markConversationRead']);
        Route::post('conversations/{id}/typing', [MessagingController::class, 'typing'])->middleware('throttle:write-action');
        Route::post('media', [MediaController::class, 'upload'])->middleware('throttle:30,1');
        Route::post('messages/upload-image', [MediaController::class, 'upload'])->middleware('throttle:30,1');
        Route::delete('media/{id}', [MediaController::class, 'delete']);
        Route::post('reports', [ReportsController::class, 'store'])->middleware('throttle:write-action');
        Route::get('me/reports', [ReportsController::class, 'mine']);
        Route::get('me/pending-results', [MatchController::class, 'pendingResults']);
        Route::get('admin/reports', [ReportsController::class, 'adminIndex']);
        Route::get('admin/reports/{id}', [ReportsController::class, 'adminShow']);
        Route::patch('admin/reports/{id}', [ReportsController::class, 'adminUpdate']);
        Route::post('venues/{id}/reviews', [VenueReviewsController::class, 'store']);
        Route::delete('reviews/{id}', [VenueReviewsController::class, 'destroy']);
        Route::get('me/tournaments', [TournamentsController::class, 'mine']);
        Route::post('tournaments/{id}/entries', [TournamentsController::class, 'enter']);
        Route::delete('tournaments/{id}/entries/{entryId}', [TournamentsController::class, 'withdraw']);
        Route::delete('tournaments/{id}/entries', [TournamentsController::class, 'withdrawMine']);

        Route::post('users/{id}/follow', [SocialController::class, 'follow'])->middleware('throttle:write-action');
        Route::delete('users/{id}/follow', [SocialController::class, 'unfollow']);
        Route::delete('users/{id}/followers/{followerId}', [SocialController::class, 'removeFollower']);
        Route::post('users/{id}/block', [SocialController::class, 'block']);
        Route::delete('users/{id}/block', [SocialController::class, 'unblock']);
        Route::get('me/blocks', [SocialController::class, 'blocks']);
        Route::post('tournaments/{id}/sign-waiver', [MedicalController::class, 'signWaiver']);
        Route::get('me/invitations', [InvitationsController::class, 'mine']);
        Route::post('invitations/{id}/accept', [InvitationsController::class, 'accept']);
        Route::post('invitations/{id}/decline', [InvitationsController::class, 'decline']);
        Route::post('squads', [SquadsController::class, 'store']);
        Route::get('squads/me', [SquadsController::class, 'mine']);
        Route::get('squads/{id}', [SquadsController::class, 'showRoute']);
        Route::patch('squads/{id}', [SquadsController::class, 'update']);
        Route::post('squads/{id}/invite', [SquadsController::class, 'invite']);
        Route::post('squads/{id}/accept', [SquadsController::class, 'accept']);
        Route::post('squads/{id}/leave', [SquadsController::class, 'leave']);
        Route::delete('squads/{id}', [SquadsController::class, 'destroy']);
        Route::get('squads/{id}/games', [SquadsController::class, 'games']);
        Route::post('stories', [StoriesController::class, 'store']);
        Route::post('stories/upload-image', [MediaController::class, 'upload'])->middleware('throttle:30,1');
        Route::get('stories/feed', [StoriesController::class, 'feed']);
        Route::post('stories/{id}/view', [StoriesController::class, 'view']);
        Route::get('stories/{id}/viewers', [StoriesController::class, 'viewers']);
        Route::post('stories/{id}/reply', [StoriesController::class, 'reply']);
        Route::delete('stories/{id}', [StoriesController::class, 'destroy']);
        Route::post('stories/{storyId}/react', [StoriesController::class, 'react']);
        Route::delete('stories/{storyId}/react', [StoriesController::class, 'unreact']);

    });

    Route::get('og/{path?}', [OgController::class, 'image'])->where('path', '.*');
});
